[build]
  base = "central-de-erros/central-de-erros/"
  command = "npm run build"
  publish="central-de-erros/central-de-erros/build/"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
